repos:
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
    - id: black
      args: ['--line-length=100']
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v7.4.0
  hooks:
    - id: eslint
      additional_dependencies:
      - eslint@7.4.0
      - eslint-config-airbnb-base@latest
      - eslint-plugin-import@2.21
      args: ['--fix']
- repo: https://gitlab.com/daverona/pre-commit-cpp
  rev: 0.6.0
  hooks:
  - id: clang-format
  - id: cpplint
    args: ['--filter=-build/namespaces,-legal/copyright,-readability/casting,-readability/todo']
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
