name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.4']
        node-version: ['10.x', '14.x']
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'Setup'
        run: julia -e "using Pkg; Pkg.add(\"PackageCompiler\")"
      - name: 'Build'
        run: npm install --build-from-source
      - name: 'Test'
        run: node test.js
